DECLARE 
    usercount NUMBER;
BEGIN
    SELECT COUNT(*) INTO usercount FROM dba_users WHERE username = 'TEST';
    IF usercount > 0 THEN
        EXECUTE IMMEDIATE 'DROP USER TEST CASCADE';
    END IF;
    EXECUTE IMMEDIATE 'CREATE USER TEST IDENTIFIED BY dev';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES TO TEST';
END;