--------------------------------------------------------
--  File created - Monday-November-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence EVENTID
--------------------------------------------------------

   CREATE SEQUENCE  TEST.EVENTID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE 
/
 --------------------------------------------------------
--  DDL for Sequence PRESCMEDICATIONID
--------------------------------------------------------

   CREATE SEQUENCE  TEST.PRESCMEDICATIONID  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE 
/
--------------------------------------------------------
--  DDL for Sequence PRESCRIPTIONID
--------------------------------------------------------

   CREATE SEQUENCE  TEST.PRESCRIPTIONID MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE 
/ 
--------------------------------------------------------
--  DDL for Procedure SPCLEARSCHEMA
--------------------------------------------------------

CREATE PROCEDURE SPCLEARSCHEMA AS 
BEGIN
  FOR c IN (SELECT table_name, constraint_name FROM user_constraints WHERE constraint_type = 'R')
  LOOP
    EXECUTE IMMEDIATE ('alter table ' || c.table_name || ' disable constraint ' || c.constraint_name);
  END LOOP;
  FOR c IN (SELECT table_name FROM user_tables)
  LOOP
    EXECUTE IMMEDIATE ('truncate table ' || c.table_name);
  END LOOP;
  FOR c IN (SELECT table_name, constraint_name FROM user_constraints WHERE constraint_type = 'R')
  LOOP
    EXECUTE IMMEDIATE ('alter table ' || c.table_name || ' enable constraint ' || c.constraint_name);
  END LOOP;
END SPCLEARSCHEMA;
/
--------------------------------------------------------
--  DDL for Table EVENT
--------------------------------------------------------

  CREATE TABLE TEST.EVENT 
   (	EVENTID NUMBER(19,0), 
	EVENTTYPE VARCHAR2(250 CHAR), 
	VERSION NUMBER(3,0),
    OCCURREDON TIMESTAMP(3),
	BODY VARCHAR2(4000), 
	STREAMID VARCHAR2(50 CHAR),
	STREAMTYPE VARCHAR2(50 CHAR),
	ISSUEDBY VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS 
/
--------------------------------------------------------
--  DDL for Table PRESCMEDICATION
--------------------------------------------------------

  CREATE TABLE TEST.PRESCMEDICATION 
   (	PRESCMEDICATIONID NUMBER(10,0), 
	PRESCRIPTIONID NUMBER(10,0), 
	MEDICATIONTYPE VARCHAR2(20 CHAR), 
	NAMEORDESC VARCHAR2(1024 CHAR), 
	POSOLOGY VARCHAR2(1024 CHAR), 
	QUANTITY NUMBER(3,0),   
	CODE VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS 
/
--------------------------------------------------------
--  DDL for Table PRESCRIPTION
--------------------------------------------------------

  CREATE TABLE TEST.PRESCRIPTION 
   (	PRESCRIPTIONID NUMBER(10,0), 
	PRESCRIPTIONTYPE VARCHAR2(5 CHAR), 
	STATUS CHAR(3 CHAR), 
	LANGUAGE CHAR(2 CHAR), 
	CREATEDON DATE, 
	DELIVERABLEAT DATE, 
	PRESCRIBERID NUMBER(10,0), 
	PRESCRIBERTYPE VARCHAR2(20 CHAR), 
	PRESCRIBERLASTNAME VARCHAR2(50 CHAR), 
	PRESCRIBERFIRSTNAME VARCHAR2(50 CHAR), 
	PRESCRIBERDISPLAYNAME VARCHAR2(100 CHAR), 
	PRESCRIBERLICENSENUM VARCHAR2(25 CHAR), 
	PRESCRIBERSSN VARCHAR2(25 CHAR), 
	PRESCRIBERSPECIALITY VARCHAR2(50 CHAR), 
	PRESCRIBERPHONE1 VARCHAR2(20 CHAR), 
	PRESCRIBERPHONE2 VARCHAR2(20 CHAR), 
	PRESCRIBEREMAIL1 VARCHAR2(50 CHAR), 
	PRESCRIBEREMAIL2 VARCHAR2(50 CHAR), 
	PRESCRIBERWEBSITE VARCHAR2(255 CHAR), 
	PRESCRIBERSTREET VARCHAR2(50 CHAR), 
	PRESCRIBERHOUSENUM VARCHAR2(10 CHAR), 
	PRESCRIBERBOXNUM VARCHAR2(10 CHAR), 
	PRESCRIBERPOSTCODE VARCHAR2(10 CHAR), 
	PRESCRIBERCITY VARCHAR2(50 CHAR), 
	PRESCRIBERCOUNTRY CHAR(2 CHAR), 
	PATIENTID NUMBER(10,0), 
	PATIENTFIRSTNAME VARCHAR2(50 CHAR), 
	PATIENTLASTNAME VARCHAR2(50 CHAR), 
	PATIENTSEX VARCHAR2(2 CHAR), 
	PATIENTSSN VARCHAR2(25 CHAR), 
	PATIENTBIRTHDATE DATE,
	ENCOUNTERID NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS 
/
--------------------------------------------------------
--  DDL for Index IX_PRESCMEDICATION_PR_38405985
--------------------------------------------------------

  CREATE INDEX TEST.IX_PRESCMEDICATION_PR_38405985 ON TEST.PRESCMEDICATION (PRESCRIPTIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS 
/
--------------------------------------------------------
--  DDL for Index PK_EVENT
--------------------------------------------------------

  CREATE UNIQUE INDEX TEST.PK_EVENT ON TEST.EVENT (EVENTID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS 
/
--------------------------------------------------------
--  DDL for Index PK_PRESCMEDICATION
--------------------------------------------------------

  CREATE UNIQUE INDEX TEST.PK_PRESCMEDICATION ON TEST.PRESCMEDICATION (PRESCMEDICATIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS 
/
--------------------------------------------------------
--  DDL for Index PK_PRESCRIPTION
--------------------------------------------------------

  CREATE UNIQUE INDEX TEST.PK_PRESCRIPTION ON TEST.PRESCRIPTION (PRESCRIPTIONID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS 
/
--------------------------------------------------------
--  Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE TEST.EVENT ADD CONSTRAINT PK_EVENT PRIMARY KEY (EVENTID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE
/
 
  ALTER TABLE TEST.EVENT MODIFY (EVENTID NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.EVENT MODIFY (EVENTTYPE NOT NULL ENABLE)
/

  ALTER TABLE TEST.EVENT MODIFY (VERSION NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.EVENT MODIFY (OCCURREDON NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.EVENT MODIFY (BODY NOT NULL ENABLE)
/

   ALTER TABLE TEST.EVENT MODIFY (STREAMID NOT NULL ENABLE)
/

  ALTER TABLE TEST.EVENT MODIFY (STREAMTYPE NOT NULL ENABLE)
/
--------------------------------------------------------
--  Constraints for Table PRESCMEDICATION
--------------------------------------------------------

  ALTER TABLE TEST.PRESCMEDICATION ADD CONSTRAINT PK_PRESCMEDICATION PRIMARY KEY (PRESCMEDICATIONID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE
/
 
  ALTER TABLE TEST.PRESCMEDICATION MODIFY (PRESCMEDICATIONID NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCMEDICATION MODIFY (PRESCRIPTIONID NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCMEDICATION MODIFY (MEDICATIONTYPE NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCMEDICATION MODIFY (NAMEORDESC NOT NULL ENABLE)
/
--------------------------------------------------------
--  Constraints for Table PRESCRIPTION
--------------------------------------------------------

  ALTER TABLE TEST.PRESCRIPTION ADD CONSTRAINT PK_PRESCRIPTION PRIMARY KEY (PRESCRIPTIONID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE
/
 
  ALTER TABLE TEST.PRESCRIPTION MODIFY (PRESCRIPTIONID NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCRIPTION MODIFY (PRESCRIPTIONTYPE NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCRIPTION MODIFY (STATUS NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCRIPTION MODIFY (LANGUAGE NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCRIPTION MODIFY (CREATEDON NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCRIPTION MODIFY (PRESCRIBERID NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCRIPTION MODIFY (PRESCRIBERTYPE NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCRIPTION MODIFY (PRESCRIBERLASTNAME NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCRIPTION MODIFY (PRESCRIBERFIRSTNAME NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCRIPTION MODIFY (PRESCRIBERDISPLAYNAME NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCRIPTION MODIFY (PRESCRIBERLICENSENUM NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCRIPTION MODIFY (PATIENTID NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCRIPTION MODIFY (PATIENTFIRSTNAME NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCRIPTION MODIFY (PATIENTLASTNAME NOT NULL ENABLE)
/
 
  ALTER TABLE TEST.PRESCRIPTION MODIFY (PATIENTSEX NOT NULL ENABLE)
/
--------------------------------------------------------
--  Ref Constraints for Table PRESCMEDICATION
--------------------------------------------------------

  ALTER TABLE TEST.PRESCMEDICATION ADD CONSTRAINT FK_PRESCMEDICATION__1901234065 FOREIGN KEY (PRESCRIPTIONID)
	  REFERENCES TEST.PRESCRIPTION (PRESCRIPTIONID) ON DELETE CASCADE ENABLE
/
--------------------------------------------------------
--  DDL for Trigger TR_EVENT
--------------------------------------------------------
create or replace trigger TEST.TR_EVENT
before insert on TEST.EVENT for each row 
begin 
  if :new.EVENTID is NULL then 
    select TEST.EVENTID.nextval into :new.EVENTID from dual;  
  end if; 
end;
/
--------------------------------------------------------
--  DDL for Trigger TR_PRESCMEDICATION
--------------------------------------------------------
create or replace trigger TEST.TR_PRESCMEDICATION
before insert on TEST.PRESCMEDICATION for each row 
begin 
  if :new.PRESCMEDICATIONID is NULL then 
    select TEST.PRESCMEDICATIONID.nextval into :new.PRESCMEDICATIONID from dual;  
  end if; 
end;
/