//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDD.HealthcareDelivery.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlServerScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlServerScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDD.HealthcareDelivery.Infrastructure.SqlServerScripts", typeof(SqlServerScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [master]
        ///GO
        ///IF EXISTS(SELECT * FROM [sys].[databases] where [name] = &apos;Test&apos;)
        ///begin
        ///ALTER DATABASE [Test] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
        ///DROP DATABASE [Test]
        ///end
        ///GO
        ////****** Object:  Database [Test]    Script Date: 16/08/2017 12:09:20 ******/
        ///CREATE DATABASE [Test]
        /// CONTAINMENT = NONE
        /// ON  PRIMARY 
        ///( NAME = N&apos;Test&apos;, FILENAME = N&apos;C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Test.mdf&apos; , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
        /// LOG ON 
        ///( NAME = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [Test]
        ///GO
        ///EXEC spClearDatabase
        ///GO
        ///INSERT [dbo].[PARAM_CACHET] ([USERNUM], [SITENUM], [SITENAME], [OPHTALMO], [TEL1], [TEL2], [ADRESSE], [NUMLOC], [MAIL1], [MAIL2], [WEB1], [WEB2], [CENTRE]) VALUES (1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0)
        ///GO
        ///INSERT [dbo].[Prescription] ([PrescriptionId], [PrescriptionType], [Status], [Language], [IsElectronic], [ElectronicNum], [CreatedOn], [DelivrableAt], [PrescriberId], [PrescriberType], [PrescriberLastName], [PrescriberFirstName], [PrescriberDisplayName], [Prescr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FindMedicationOrdersById {
            get {
                return ResourceManager.GetString("FindMedicationOrdersById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [Test]
        ///GO
        ///EXEC spClearDatabase
        ///GO
        ///INSERT [dbo].[Prescription] ([PrescriptionId], [PrescriptionType], [Status], [Language], [IsElectronic], [ElectronicNum], [CreatedOn], [DelivrableAt], [PrescriberId], [PrescriberType], [PrescriberLastName], [PrescriberFirstName], [PrescriberDisplayName], [PrescriberLicenseNum], [PrescriberSSN], [PrescriberSpeciality], [PrescriberPhone1], [PrescriberPhone2], [PrescriberEmail1], [PrescriberEmail2], [PrescriberWebSite], [PrescriberStreet], [PrescriberHouseNum], [Prescr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FindPharmaceuticalPrescriptionsByPatient {
            get {
                return ResourceManager.GetString("FindPharmaceuticalPrescriptionsByPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [Test]
        ///GO
        ///EXEC spClearDatabase
        ///GO
        ///INSERT [dbo].[PARAM_CACHET] ([USERNUM], [SITENUM], [SITENAME], [OPHTALMO], [TEL1], [TEL2], [ADRESSE], [NUMLOC], [MAIL1], [MAIL2], [WEB1], [WEB2], [CENTRE]) VALUES (1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0)
        ///GO
        ///INSERT [dbo].[Prescription] ([PrescriptionId], [PrescriptionType], [Status], [Language], [IsElectronic], [ElectronicNum], [CreatedOn], [DelivrableAt], [PrescriberId], [PrescriberType], [PrescriberLastName], [PrescriberFirstName], [PrescriberDisplayName], [Prescr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FindPrescribedMedicationsByPrescription {
            get {
                return ResourceManager.GetString("FindPrescribedMedicationsByPrescription", resourceCulture);
            }
        }
    }
}
