//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDD.HealthcareDelivery.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDD.HealthcareDelivery.Infrastructure.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT   PrescriptionId AS Identifier,
        ///         CASE Status
        ///			WHEN &apos;CRT&apos; THEN 0
        ///			WHEN &apos;INP&apos; THEN 1
        ///			WHEN &apos;DLV&apos; THEN 2
        ///			WHEN &apos;RVK&apos; THEN 3
        ///			WHEN &apos;EXP&apos; THEN 4
        ///			WHEN &apos;ARC&apos; THEN 5
        ///		 END AS Status,
        ///         CreatedOn,
        ///         DeliverableAt,
        ///		 PrescriberDisplayName
        ///FROM     Prescription
        ///WHERE    PrescriptionType = &apos;PHARM&apos;
        ///AND      PatientId = @PatientId
        ///ORDER BY CreatedOn, PrescriptionId.
        /// </summary>
        internal static string FindPharmaceuticalPrescriptionsByPatient {
            get {
                return ResourceManager.GetString("FindPharmaceuticalPrescriptionsByPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT   PrescMedicationId As Identifier,
        ///		 NameOrDesc AS NameOrDescription,
        ///         Posology,
        ///         Quantity,
        ///         Code
        ///FROM     PrescMedication
        ///WHERE    PrescriptionId = @PrescriptionId
        ///ORDER BY NameOrDesc.
        /// </summary>
        internal static string FindPrescribedMedicationsByPrescription {
            get {
                return ResourceManager.GetString("FindPrescribedMedicationsByPrescription", resourceCulture);
            }
        }
    }
}
